import os
import io
from PIL import Image
import streamlit as st
import google.generativeai as genai
from langchain_google_genai import ChatGoogleGenerativeAI

# ==== Setup ====
st.set_page_config(page_title="Car Damage Estimator", layout="centered")
st.title("🚗 Car Damage Estimator")
st.write("Upload an image of your car, and get damage analysis & repair cost estimation.")

# ===== Google API Key =====
os.environ["GOOGLE_API_KEY"] = ""
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

# ==== Initialize LLM Models ====
# LangChain LLM for cost estimation
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.4
)

# Config for vision model
llm_config = {
    "temperature": 0.4,
    "top_p": 0.95,
    "top_k": 40,
    "max_output_tokens": 2048,
}

# ==== Upload Image ====
uploaded_file = st.file_uploader("📤 Upload Car Image", type=["png", "jpg", "jpeg"])

if uploaded_file:
    # Read image into memory
    image_bytes = uploaded_file.read()
    image = Image.open(io.BytesIO(image_bytes))
    st.image(image, caption="Uploaded Car Image", use_column_width=True)

    if st.button("🚗 Analyze Damage"):
        # ==== Damage Analysis (Vision Model) ====
        st.info("🔍 Analyzing damage...")
        
        # Use vision model for image analysis - FIXED MODEL NAME
        vision_model = genai.GenerativeModel(
            model_name="gemini-2.5-flash",  # Changed from gemini-1.5-flash
            generation_config=llm_config
        )
        
        damage_prompt = """You are a vehicle damage expert.
Analyze this car image and:
1. Identify all visible damage (dents, scratches, broken parts, etc.)
2. Specify the location of damage (front bumper, door, hood, etc.)
3. Assess severity (minor, moderate, severe)
4. Provide a brief repair description"""

        # Reopen image for analysis
        image_for_analysis = Image.open(io.BytesIO(image_bytes))
        damage_response = vision_model.generate_content([damage_prompt, image_for_analysis])
        damage_info = damage_response.text
        
        st.success("✅ Damage Analysis Completed")
        st.markdown("### 📋 Damage Analysis")
        st.markdown(damage_info)

        # ==== Cost Estimation (LangChain LLM) ====
        st.info("💰 Estimating repair cost...")
        
        cost_prompt = f"""You are an insurance cost estimator.

Vehicle: Toyota Corolla 2020
Damage Details:
{damage_info}

Provide a detailed cost estimation with:
1. Itemized repair costs (parts + labor)
2. Total estimated cost in USD
3. Damage category: Minor (<$500), Moderate ($500-$2000), Major (>$2000)
4. Estimated repair time
5. Recommendations (repair vs replace)

Format your response clearly with sections."""

        # Use LangChain LLM for cost estimation
        cost_response = llm.invoke(cost_prompt)
        cost_info = cost_response.content
        
        st.success("💰 Cost Estimation Completed")
        st.markdown("### 💵 Cost Estimation")
        st.markdown(cost_info)

        # ==== Generate Report ====
        report_text = f"""CAR DAMAGE ESTIMATION REPORT
{'='*50}

Vehicle Information:
- Make/Model: Toyota Corolla
- Year: 2020

{'='*50}
DAMAGE ANALYSIS
{'='*50}
{damage_info}

{'='*50}
COST ESTIMATION
{'='*50}
{cost_info}

{'='*50}
Report generated by Car Damage Estimator
"""
        
        st.divider()
        st.success("✅ Report generated successfully")
        st.download_button(
            label="📥 Download Full Report",
            data=report_text,
            file_name="car_damage_report.txt",
            mime="text/plain",
            use_container_width=True

        )

